---
- name: Deploy Webapp
  hosts: web
  become: true

  tasks:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Deploy Application from Github
      block:
        - name: Create Temporary Directory
          ansible.builtin.tempfile:
            state: directory
          register: aw_app_directory
          delegate_to: localhost
          run_once: true

        - name: Clone Application Repository
          ansible.builtin.git:
            repo: https://github.com/mhyclak-silex/aw_app.git
            dest: "{{ aw_app_directory.path }}"
            version: "{{ aw_app_branch | d('main') }}"
          delegate_to: localhost
          run_once: true

        - name: Debug Application Repository
          ansible.builtin.command: "ls -l {{ aw_app_directory.path }}"
          changed_when: false
          delegate_to: localhost
          run_once: true

        - name: Deploy index.html
          ansible.builtin.template:
            src: "{{ aw_app_directory.path }}/index.html.j2"
            dest: /var/www/html/index.html
            mode: 0755
      always:
        - name: Cleanup Temporary Directory
          ansible.builtin.file:
            path: "{{ aw_app_directory.path }}"
            state: absent
          delegate_to: localhost
          run_once: true

    - name: Validate Application
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}
      register: uri_results

    - name: Show Validation
      ansible.builtin.debug:
        var: uri_results
