---
all:
  children:
    linux:
      children:
        linux_dev:
          hosts:
           linuxdev1.example.com: {}
           linuxdev2.example.com: {}
        linux_qa:
          hosts:
           linuxqa1.example.com: {}
           linuxqa2.example.com: {}
        linux_prod:
          hosts:
           linuxprod1.example.com: {}
           linuxprod2.example.com: {}
    windows:
      children:
        domain_controllers:
          hosts:
            ad1.example.com: {}
            ad2.example.com: {}
